name: "dradis-ce"

services:
  web:
    image: dradis/dradis-ce:4.18.0
    volumes:
      # Persist the database
      - dradis-ce-storage:/dradis/storage
    ports:
      - 443:443
      - 80:80
    environment:
      # Set domain from .env so thruster can handle let's encrypt certificates
      - TLS_DOMAIN=${TLS_DOMAIN}
    healthcheck:
      test: [
        "CMD-SHELL", 
        "if [ \"$TLS_DOMAIN\" ]; then curl -f -k http://$TLS_DOMAIN/up; else curl -f http://localhost/up; fi"
      ]
      timeout: 15s
      retries: 3
volumes:
  dradis-ce-storage:
